/* ============================================================================
   MV26020 — Gestión y Cálculo de Listas de Precio
   PORTAL (aplicativo web) · Script 06 — EXTENSIÓN PARA ROL APROBADOR
   
   ADAPTADO A SCHEMA REAL:
   - Tabla base: SOLICITUD (no SOLICITUD_PRECIO)
   - Tabla detalle: SOLICITUD_DETALLE (no SOLICITUD_PRECIO_DETALLE)

   PROPÓSITO:
   Agregar columnas a SOLICITUD para soportar flujo de aprobación y crear
   tablas de soporte para reintentos y auditoría granular del aprobador.

   REGLAS CUBIERTAS:
     - RF-20: FECHA_REVISION (Aprobador abre detalle)
     - RF-26: FECHA_INICIO_EJECUCION, FECHA_FIN_EJECUCION
     - RF-29/RF-30: SOLICITUD_REINTENTO (reintentos hasta 3 veces)
     - RF-31: ES_ERROR_TRANSITORIO, CODIGO_ERROR, MENSAJE_ERROR
     - RF-32: AUDITORIA_APROBACION (decisiones de aprobador)
     - HU-12: CANCELACION_SOLICITADA, CANCELACION_CONFIRMADA

   IDEMPOTENCIA: Solo agrega/actualiza si falta; no crea duplicados.
   ============================================================================ */

:setvar DB_PORTAL "SOFTLANDQA"
GO

USE [$(DB_PORTAL)];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

PRINT '=== INICIANDO SCRIPT 06: EXTENSIÓN PARA ROL APROBADOR ===';
GO

/* ============================================================================
   6.1 EXTENSIÓN DE SOLICITUD — Columnas para Aprobador
   ============================================================================ */

PRINT 'Paso 1: Agregando columnas de error transitorio (RF-31)...';
IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'ES_ERROR_TRANSITORIO') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [ES_ERROR_TRANSITORIO] CHAR(1) NOT NULL CONSTRAINT [DF_SOLICITUD_ERROR_TRANS] DEFAULT ('N');
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'CODIGO_ERROR') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [CODIGO_ERROR] VARCHAR(40) NULL;
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'MENSAJE_ERROR') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [MENSAJE_ERROR] VARCHAR(1000) NULL;
GO

PRINT 'Paso 2: Agregando columna de revisión (RF-20)...';
IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'FECHA_REVISION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [FECHA_REVISION] DATETIME NULL;
GO

PRINT 'Paso 3: Agregando columnas de ejecución (RF-26)...';
IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'FECHA_INICIO_EJECUCION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [FECHA_INICIO_EJECUCION] DATETIME NULL;
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'FECHA_FIN_EJECUCION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [FECHA_FIN_EJECUCION] DATETIME NULL;
GO

PRINT 'Paso 4: Agregando columnas de cancelación (HU-12)...';
IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'CANCELACION_SOLICITADA') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [CANCELACION_SOLICITADA] CHAR(1) NOT NULL CONSTRAINT [DF_SOLICITUD_CANC_SOL] DEFAULT ('N');
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'FECHA_SOLICITUD_CANCELACION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [FECHA_SOLICITUD_CANCELACION] DATETIME NULL;
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'USUARIO_SOLICITA_CANCELACION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [USUARIO_SOLICITA_CANCELACION] VARCHAR(120) NULL;
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'CANCELACION_CONFIRMADA') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [CANCELACION_CONFIRMADA] CHAR(1) NOT NULL CONSTRAINT [DF_SOLICITUD_CANC_CONF] DEFAULT ('N');
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'FECHA_CANCELACION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [FECHA_CANCELACION] DATETIME NULL;
GO

IF COL_LENGTH(N'[PORTAL_PRECIOS].[SOLICITUD]', 'USUARIO_DECIDE_CANCELACION') IS NULL
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD]
        ADD [USUARIO_DECIDE_CANCELACION] VARCHAR(120) NULL;
GO

PRINT 'Paso 5: Agregando CHECK constraints...';

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_SOLICITUD_ERROR_TRANS')
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD] WITH CHECK
        ADD CONSTRAINT [CK_SOLICITUD_ERROR_TRANS] CHECK ([ES_ERROR_TRANSITORIO] IN ('S','N'));
GO

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_SOLICITUD_CANC_SOLICITADA')
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD] WITH CHECK
        ADD CONSTRAINT [CK_SOLICITUD_CANC_SOLICITADA] CHECK ([CANCELACION_SOLICITADA] IN ('S','N'));
GO

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_SOLICITUD_CANC_CONFIRMADA')
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD] WITH CHECK
        ADD CONSTRAINT [CK_SOLICITUD_CANC_CONFIRMADA] CHECK ([CANCELACION_CONFIRMADA] IN ('S','N'));
GO

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_SOLICITUD_CANC_LOGICA')
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD] WITH CHECK
        ADD CONSTRAINT [CK_SOLICITUD_CANC_LOGICA] CHECK (
            [CANCELACION_CONFIRMADA] = 'N' OR [CANCELACION_SOLICITADA] = 'S'
        );
GO

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_SOLICITUD_FECHAS_EJEC')
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD] WITH CHECK
        ADD CONSTRAINT [CK_SOLICITUD_FECHAS_EJEC] CHECK (
            [FECHA_FIN_EJECUCION] IS NULL OR [FECHA_INICIO_EJECUCION] IS NOT NULL
        );
GO

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_SOLICITUD_INTENTO_RANGO')
    ALTER TABLE [PORTAL_PRECIOS].[SOLICITUD] WITH CHECK
        ADD CONSTRAINT [CK_SOLICITUD_INTENTO_RANGO] CHECK ([INTENTOS_REINTENTO] BETWEEN 0 AND 3);
GO

/* ============================================================================
   6.2 SOLICITUD_REINTENTO — Rastreo de Reintentos Transitorios (RF-29/RF-30)
   ============================================================================ */

PRINT 'Paso 6: Creando tabla SOLICITUD_REINTENTO...';

IF OBJECT_ID(N'[PORTAL_PRECIOS].[SOLICITUD_REINTENTO]', N'U') IS NULL
BEGIN
    CREATE TABLE [PORTAL_PRECIOS].[SOLICITUD_REINTENTO]
    (
        [ID_REINTENTO]                    BIGINT IDENTITY(1,1) NOT NULL,
        [ID_SOLICITUD]                    INT          NOT NULL,
        [INTENTO_NUMERO]                  TINYINT      NOT NULL,
        [FECHA_INTENTO]                   DATETIME     NOT NULL CONSTRAINT [DF_REINTENTO_FECHA] DEFAULT (GETDATE()),
        [TIPO_ERROR]                      VARCHAR(40)  NOT NULL,
        [CODIGO_ERROR]                    VARCHAR(40)  NULL,
        [MENSAJE_ERROR]                   VARCHAR(1000) NULL,
        [BACKOFF_SEGUNDOS]                INT          NULL,
        [PROXIMO_REINTENTO_PROGRAMADO]    DATETIME     NULL,
        [RESULTADO_REINTENTO]             VARCHAR(15)  NULL,
        [NOTAS]                           VARCHAR(500) NULL,
        CONSTRAINT [PK_SOLICITUD_REINTENTO] PRIMARY KEY CLUSTERED ([ID_REINTENTO]),
        CONSTRAINT [FK_REINTENTO_SOLICITUD] FOREIGN KEY ([ID_SOLICITUD])
            REFERENCES [PORTAL_PRECIOS].[SOLICITUD] ([ID_SOLICITUD]) ON DELETE CASCADE,
        CONSTRAINT [CK_REINTENTO_INTENTO] CHECK ([INTENTO_NUMERO] BETWEEN 1 AND 3),
        CONSTRAINT [CK_REINTENTO_TIPO_ERROR] CHECK ([TIPO_ERROR] IN
            ('connection_timeout','temporary_lock','service_unavailable','transient_database_error','other_transient')),
        CONSTRAINT [CK_REINTENTO_RESULTADO] CHECK ([RESULTADO_REINTENTO] IS NULL OR [RESULTADO_REINTENTO] IN ('PENDIENTE','EXITOSO','FALLIDO'))
    );

    CREATE INDEX [IX_REINTENTO_SOLICITUD_INTENTO]
        ON [PORTAL_PRECIOS].[SOLICITUD_REINTENTO] ([ID_SOLICITUD], [INTENTO_NUMERO]);
    CREATE INDEX [IX_REINTENTO_PROXIMO]
        ON [PORTAL_PRECIOS].[SOLICITUD_REINTENTO] ([PROXIMO_REINTENTO_PROGRAMADO])
        WHERE [PROXIMO_REINTENTO_PROGRAMADO] IS NOT NULL AND [RESULTADO_REINTENTO] IS NULL;
    CREATE INDEX [IX_REINTENTO_FECHA]
        ON [PORTAL_PRECIOS].[SOLICITUD_REINTENTO] ([FECHA_INTENTO] DESC);
END
GO

/* ============================================================================
   6.3 AUDITORIA_APROBACION — Auditoría Granular de Decisiones de Aprobador
   ============================================================================ */

PRINT 'Paso 7: Creando tabla AUDITORIA_APROBACION...';

IF OBJECT_ID(N'[PORTAL_PRECIOS].[AUDITORIA_APROBACION]', N'U') IS NULL
BEGIN
    CREATE TABLE [PORTAL_PRECIOS].[AUDITORIA_APROBACION]
    (
        [ID_APROBACION]             BIGINT IDENTITY(1,1) NOT NULL,
        [ID_SOLICITUD]              INT          NOT NULL,
        [FECHA]                     DATETIME     NOT NULL CONSTRAINT [DF_AUDITORIA_FECHA] DEFAULT (GETDATE()),
        [USUARIO_EMAIL]             VARCHAR(120) NOT NULL,
        [USUARIO_NOMBRE]            VARCHAR(120) NULL,
        [ACCION]                    VARCHAR(30)  NOT NULL,
        [ESTADO_ANTERIOR]           VARCHAR(25)  NULL,
        [ESTADO_NUEVO]              VARCHAR(25)  NULL,
        [COMENTARIO_DECISION]       VARCHAR(1000) NULL,
        [IMPACTO_CONFIRMADO]        VARCHAR(500) NULL,
        [RESULTADO_EJECUCION]       VARCHAR(15)  NULL,
        [DETALLE_JSON]              NVARCHAR(MAX) NULL,
        CONSTRAINT [PK_AUDITORIA_APROBACION] PRIMARY KEY CLUSTERED ([ID_APROBACION]),
        CONSTRAINT [FK_AUDITORIA_SOLICITUD] FOREIGN KEY ([ID_SOLICITUD])
            REFERENCES [PORTAL_PRECIOS].[SOLICITUD] ([ID_SOLICITUD]) ON DELETE CASCADE,
        CONSTRAINT [CK_AUDITORIA_ACCION] CHECK ([ACCION] IN
            ('APROBADA','RECHAZADA','CANCELACION_SOLICITADA','CANCELACION_CONFIRMADA','CANCELACION_DENEGADA','REPROCESO_AUTORIZADO')),
        CONSTRAINT [CK_AUDITORIA_RECHAZO] CHECK (
            [ACCION] <> 'RECHAZADA' OR ([COMENTARIO_DECISION] IS NOT NULL AND LEN(LTRIM(RTRIM([COMENTARIO_DECISION]))) > 0)
        )
    );

    CREATE INDEX [IX_AUDITORIA_SOLICITUD_FECHA]
        ON [PORTAL_PRECIOS].[AUDITORIA_APROBACION] ([ID_SOLICITUD], [FECHA] DESC);
    CREATE INDEX [IX_AUDITORIA_USUARIO_FECHA]
        ON [PORTAL_PRECIOS].[AUDITORIA_APROBACION] ([USUARIO_EMAIL], [FECHA] DESC);
    CREATE INDEX [IX_AUDITORIA_ACCION]
        ON [PORTAL_PRECIOS].[AUDITORIA_APROBACION] ([ACCION], [FECHA] DESC);
END
GO

/* ============================================================================
   6.4 Resumen y Validación
   ============================================================================ */

PRINT '';
PRINT '========== RESUMEN DEL SCRIPT 06 ==========';
PRINT 'Cambios realizados:';
PRINT '  1. Agregadas 9 columnas a SOLICITUD (cancelación, error, ejecución)';
PRINT '  2. Creada tabla SOLICITUD_REINTENTO (reintentos transitorios)';
PRINT '  3. Creada tabla AUDITORIA_APROBACION (auditoría de aprobador)';
PRINT '  4. Agregados 6 CHECK constraints';
PRINT '  5. Creados 6 índices nuevos';
PRINT '';
PRINT 'Nuevas columnas en SOLICITUD:';
PRINT '  - ES_ERROR_TRANSITORIO (CHAR(1))';
PRINT '  - CODIGO_ERROR (VARCHAR(40))';
PRINT '  - MENSAJE_ERROR (VARCHAR(1000))';
PRINT '  - FECHA_REVISION (DATETIME)';
PRINT '  - FECHA_INICIO_EJECUCION (DATETIME)';
PRINT '  - FECHA_FIN_EJECUCION (DATETIME)';
PRINT '  - CANCELACION_SOLICITADA (CHAR(1))';
PRINT '  - FECHA_SOLICITUD_CANCELACION (DATETIME)';
PRINT '  - USUARIO_SOLICITA_CANCELACION (VARCHAR(120))';
PRINT '  - CANCELACION_CONFIRMADA (CHAR(1))';
PRINT '  - FECHA_CANCELACION (DATETIME)';
PRINT '  - USUARIO_DECIDE_CANCELACION (VARCHAR(120))';
PRINT '';
PRINT 'Nuevas tablas:';
PRINT '  - SOLICITUD_REINTENTO (BIGINT, rastreo de reintentos)';
PRINT '  - AUDITORIA_APROBACION (BIGINT, auditoría de decisiones)';
PRINT '';
PRINT 'Cobertura:';
PRINT '  - RF-20: Modal de confirmación con FECHA_REVISION';
PRINT '  - RF-26: Timestamps de ejecución (FECHA_INICIO, FECHA_FIN)';
PRINT '  - RF-29/RF-30: SOLICITUD_REINTENTO con límite de 3 intentos';
PRINT '  - RF-31: Clasificación de errores transitorios';
PRINT '  - RF-32: AUDITORIA_APROBACION para decisiones granulares';
PRINT '  - HU-12: Cancelación solicitada/confirmada/denegada';
PRINT '';
PRINT '========== FIN DEL SCRIPT 06 ==========';
PRINT '';
PRINT 'SCRIPT 06 completado exitosamente.';
GO
