USE [MAR];
GO

/*
  Versión QA. Conserva PRECIO publicado y U_PRECIO_TECNICO dentro de
  ARTICULO_PRECIO. La columna de descuento contiene un porcentaje 0..100:

  FACTOR_DESCUENTO = 1 - U_DCTO_LPVn / 100
  PRECIO_TECNICO_DESTINO = PRECIO_TECNICO_BASE
                         * FACTOR_DESCUENTO
                         * FACTOR_GLOBAL
                         * FACTOR_ARTICULO
  PRECIO_DESTINO = FN_REDONDEAR_PRECIO(PRECIO_TECNICO_DESTINO)

  Para MAYOREOB 30 % sobre MAYOREOD técnica:
  @P_NIVEL_PRECIO_BASE='MAYOREOD', @P_FACTOR_GLOBAL=1.30,
  @COLUMNA_DCTO=NULL.
*/
CREATE OR ALTER PROCEDURE COFER.SP_GESTION_LISTAS_PRECIOS_FULL_QA_V2
    @P_NIVEL_PRECIO VARCHAR(50),
    @P_FECHA_INICIO DATE,
    @P_FECHA_FIN DATE,
    @P_NIVEL_PRECIO_BASE VARCHAR(50),
    @P_VERSION INT,
    @COLUMNA_DCTO VARCHAR(20)=NULL,
    @P_FACTOR_GLOBAL DECIMAL(18,8)=1.0,
    @P_EXTENDER_MAYOR_100000 BIT=0,
    @P_SOLO_SIMULAR BIT=1
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  IF @P_FECHA_INICIO IS NULL OR @P_FECHA_FIN IS NULL
     OR @P_FECHA_INICIO>@P_FECHA_FIN
    THROW 51001,'Rango de fechas inválido.',1;

  IF @P_FACTOR_GLOBAL<=0 OR @P_FACTOR_GLOBAL>2
    THROW 51002,'Factor global fuera de rango.',1;

  IF (SELECT COUNT(*) FROM COFER.VERSION_NIVEL
      WHERE NIVEL_PRECIO=@P_NIVEL_PRECIO
        AND VERSION=@P_VERSION AND ESTADO='A')<>1
    THROW 51008,'La versión destino no existe, no está activa o es ambigua.',1;

  IF @COLUMNA_DCTO IS NOT NULL
     AND NOT EXISTS
     (
       SELECT 1 FROM sys.columns
       WHERE object_id=OBJECT_ID(N'COFER.ARTICULO')
         AND name=@COLUMNA_DCTO
         AND name LIKE 'U_DCTO_LPV%'
     )
    THROW 51003,'Columna de descuento inexistente o no autorizada.',1;

  IF EXISTS
  (
    SELECT 1
    FROM COFER.ARTICULO_PRECIO AP
    JOIN COFER.VERSION_NIVEL VN
      ON VN.NIVEL_PRECIO=AP.NIVEL_PRECIO AND VN.VERSION=AP.VERSION
    WHERE AP.NIVEL_PRECIO=@P_NIVEL_PRECIO_BASE
      AND VN.ESTADO='A'
      AND AP.U_PRECIO_TECNICO IS NULL
  )
    THROW 51004,'La lista base contiene precios técnicos nulos.',1;

  CREATE TABLE #FACTOR_ARTICULO
  (
    ARTICULO VARCHAR(50) NOT NULL PRIMARY KEY,
    FACTOR DECIMAL(18,8) NOT NULL
  );

  IF @P_NIVEL_PRECIO_BASE='MAYOREO'
     AND @P_NIVEL_PRECIO<>'MAYOREO'
  BEGIN
    IF EXISTS
    (
      SELECT U_ARTICULO
      FROM COFER.U_FACTOR_ARTICULO
      GROUP BY U_ARTICULO
      HAVING COUNT(*)>1
    )
      THROW 51009,'Hay más de un factor por artículo.',1;

    INSERT #FACTOR_ARTICULO(ARTICULO,FACTOR)
    SELECT U_ARTICULO,CAST(U_FACTOR AS DECIMAL(18,8))
    FROM COFER.U_FACTOR_ARTICULO;
  END;

  CREATE TABLE #BASE_CALCULO
  (
    NIVEL_PRECIO VARCHAR(50),MONEDA VARCHAR(10),VERSION_DESTINO INT,
    ARTICULO VARCHAR(50),VERSION_ARTICULO INT,
    PRECIO_TECNICO_BASE DECIMAL(28,8),FACTOR_DESCUENTO DECIMAL(18,8),
    FACTOR_GLOBAL DECIMAL(18,8),FACTOR_ARTICULO DECIMAL(18,8),
    FACTOR_FINAL DECIMAL(18,8),PRECIO_TECNICO_DESTINO DECIMAL(28,8),
    ESQUEMA_TRABAJO VARCHAR(50),MARGEN_UTILIDAD_MIN DECIMAL(28,8),
    COSTO_PROM_DOL DECIMAL(28,8)
  );

  DECLARE @EXPRESION_DCTO NVARCHAR(MAX)=CASE
    WHEN @COLUMNA_DCTO IS NULL THEN N'CAST(1.0 AS DECIMAL(18,8))'
    ELSE N'CAST(1.0-(CAST(COALESCE(A.'+QUOTENAME(@COLUMNA_DCTO)+
         N',0) AS DECIMAL(18,8))/100.0) AS DECIMAL(18,8))' END;

  DECLARE @SQL NVARCHAR(MAX)=N'
    INSERT #BASE_CALCULO
    SELECT @DESTINO,AP.MONEDA,@VERSION,AP.ARTICULO,AP.VERSION_ARTICULO,
           AP.U_PRECIO_TECNICO,F.FACTOR_DESCUENTO,@FACTOR_GLOBAL,
           COALESCE(FA.FACTOR,CAST(1 AS DECIMAL(18,8))),X.FACTOR_FINAL,
           CAST(AP.U_PRECIO_TECNICO*X.FACTOR_FINAL AS DECIMAL(28,8)),
           AP.ESQUEMA_TRABAJO,AP.MARGEN_UTILIDAD_MIN,
           CAST(A.COSTO_PROM_DOL AS DECIMAL(28,8))
    FROM COFER.ARTICULO_PRECIO AP
    JOIN COFER.VERSION_NIVEL VN
      ON VN.NIVEL_PRECIO=AP.NIVEL_PRECIO
     AND VN.VERSION=AP.VERSION AND VN.ESTADO=''A''
    JOIN COFER.ARTICULO A ON A.ARTICULO=AP.ARTICULO
    LEFT JOIN #FACTOR_ARTICULO FA ON FA.ARTICULO=AP.ARTICULO
    CROSS APPLY (SELECT '+@EXPRESION_DCTO+N') F(FACTOR_DESCUENTO)
    CROSS APPLY
    (
      SELECT CAST(F.FACTOR_DESCUENTO*@FACTOR_GLOBAL*
                  COALESCE(FA.FACTOR,1.0) AS DECIMAL(18,8))
    ) X(FACTOR_FINAL)
    WHERE AP.NIVEL_PRECIO=@BASE
      AND AP.U_PRECIO_TECNICO>0;';

  EXEC sys.sp_executesql @SQL,
    N'@DESTINO VARCHAR(50),@BASE VARCHAR(50),@VERSION INT,
      @FACTOR_GLOBAL DECIMAL(18,8)',
    @DESTINO=@P_NIVEL_PRECIO,@BASE=@P_NIVEL_PRECIO_BASE,
    @VERSION=@P_VERSION,@FACTOR_GLOBAL=@P_FACTOR_GLOBAL;

  IF NOT EXISTS(SELECT 1 FROM #BASE_CALCULO)
    THROW 51005,'No hay precios base activos para calcular.',1;

  IF EXISTS(SELECT 1 FROM #BASE_CALCULO WHERE FACTOR_FINAL<=0 OR FACTOR_FINAL>2)
    THROW 51006,'Existe un factor final fuera del rango (0,2].',1;

  SELECT B.*,R.PRECIO_REDONDEADO,R.TRAMO,R.ESTADO,
    CAST(CASE WHEN R.PRECIO_REDONDEADO>0 AND B.COSTO_PROM_DOL IS NOT NULL
      THEN 1-B.COSTO_PROM_DOL/R.PRECIO_REDONDEADO END AS DECIMAL(28,8))
      MARGEN_UTILIDAD_CALC,
    /* Se conserva la fórmula histórica hasta que Finanzas defina MARGEN_MULR. */
    CAST(CASE WHEN B.PRECIO_TECNICO_BASE>0 AND B.FACTOR_FINAL>0
                   AND B.COSTO_PROM_DOL IS NOT NULL
      THEN 1-B.COSTO_PROM_DOL/(B.PRECIO_TECNICO_BASE/B.FACTOR_FINAL)
      END AS DECIMAL(28,8)) MARGEN_MULR_CALC
  INTO #CALCULO
  FROM #BASE_CALCULO B
  CROSS APPLY COFER.FN_REDONDEAR_PRECIO
    (B.PRECIO_TECNICO_DESTINO,@P_EXTENDER_MAYOR_100000) R;

  SELECT *,CAST(CASE
    WHEN ESTADO<>'OK' THEN ESTADO
    WHEN COSTO_PROM_DOL IS NULL THEN 'COSTO_NO_DISPONIBLE'
    WHEN PRECIO_REDONDEADO<COSTO_PROM_DOL THEN 'PRECIO_BAJO_COSTO'
    WHEN MARGEN_UTILIDAD_MIN IS NOT NULL
      AND MARGEN_UTILIDAD_CALC<MARGEN_UTILIDAD_MIN THEN 'MARGEN_INSUFICIENTE'
    ELSE 'OK' END AS VARCHAR(30)) VALIDACION
  FROM #CALCULO
  ORDER BY ARTICULO,MONEDA;

  IF @P_SOLO_SIMULAR=1 RETURN;

  IF EXISTS
  (
    SELECT 1 FROM #CALCULO
    WHERE ESTADO<>'OK' OR COSTO_PROM_DOL IS NULL
       OR PRECIO_REDONDEADO<COSTO_PROM_DOL
       OR (MARGEN_UTILIDAD_MIN IS NOT NULL
           AND MARGEN_UTILIDAD_CALC<MARGEN_UTILIDAD_MIN)
  )
    THROW 51007,'Publicación cancelada por validaciones.',1;

  BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE AP
    SET AP.U_PRECIO_TECNICO=C.PRECIO_TECNICO_DESTINO,
        AP.PRECIO=C.PRECIO_REDONDEADO,
        AP.MARGEN_UTILIDAD=C.MARGEN_UTILIDAD_CALC,
        AP.MARGEN_MULR=C.MARGEN_MULR_CALC,
        AP.FECHA_INICIO=@P_FECHA_INICIO,
        AP.FECHA_FIN=@P_FECHA_FIN,
        AP.FECHA_ULT_MODIF=GETDATE(),
        AP.USUARIO_ULT_MODIF='SA'
    FROM COFER.ARTICULO_PRECIO AP WITH(UPDLOCK,HOLDLOCK)
    JOIN #CALCULO C
      ON C.NIVEL_PRECIO=AP.NIVEL_PRECIO
     AND C.MONEDA=AP.MONEDA
     AND C.VERSION_DESTINO=AP.VERSION
     AND C.ARTICULO=AP.ARTICULO
     AND C.VERSION_ARTICULO=AP.VERSION_ARTICULO
    WHERE EXISTS
    (
      SELECT AP.U_PRECIO_TECNICO,AP.PRECIO,AP.MARGEN_UTILIDAD,
             AP.MARGEN_MULR,AP.FECHA_INICIO,AP.FECHA_FIN
      EXCEPT
      SELECT C.PRECIO_TECNICO_DESTINO,C.PRECIO_REDONDEADO,
             C.MARGEN_UTILIDAD_CALC,C.MARGEN_MULR_CALC,
             @P_FECHA_INICIO,@P_FECHA_FIN
    );

    INSERT COFER.ARTICULO_PRECIO
    (NIVEL_PRECIO,MONEDA,VERSION,ARTICULO,VERSION_ARTICULO,
     PRECIO,U_PRECIO_TECNICO,ESQUEMA_TRABAJO,MARGEN_MULR,
     MARGEN_UTILIDAD,FECHA_INICIO,FECHA_FIN,FECHA_ULT_MODIF,
     USUARIO_ULT_MODIF,MARGEN_UTILIDAD_MIN)
    SELECT C.NIVEL_PRECIO,C.MONEDA,C.VERSION_DESTINO,C.ARTICULO,
           C.VERSION_ARTICULO,C.PRECIO_REDONDEADO,C.PRECIO_TECNICO_DESTINO,
           C.ESQUEMA_TRABAJO,C.MARGEN_MULR_CALC,C.MARGEN_UTILIDAD_CALC,
           @P_FECHA_INICIO,@P_FECHA_FIN,GETDATE(),'SA',C.MARGEN_UTILIDAD_MIN
    FROM #CALCULO C
    WHERE NOT EXISTS
    (
      SELECT 1 FROM COFER.ARTICULO_PRECIO AP WITH(UPDLOCK,HOLDLOCK)
      WHERE AP.NIVEL_PRECIO=C.NIVEL_PRECIO
        AND AP.MONEDA=C.MONEDA
        AND AP.VERSION=C.VERSION_DESTINO
        AND AP.ARTICULO=C.ARTICULO
        AND AP.VERSION_ARTICULO=C.VERSION_ARTICULO
    );

    COMMIT TRANSACTION;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH;
END;
GO

/* LPV2: descuento porcentual desde MAYOREO. */
/*
EXEC COFER.SP_GESTION_LISTAS_PRECIOS_FULL_QA_V2
 @P_NIVEL_PRECIO='LPV2',@P_FECHA_INICIO='20260910',
 @P_FECHA_FIN='99991231',@P_NIVEL_PRECIO_BASE='MAYOREO',
 @P_VERSION=1,@COLUMNA_DCTO='U_DCTO_LPV2',
 @P_FACTOR_GLOBAL=1,@P_EXTENDER_MAYOR_100000=0,@P_SOLO_SIMULAR=1;
*/

/* MAYOREOB: aumento de 30 % sobre MAYOREOD técnica, sin descuento LPV. */
/*
EXEC COFER.SP_GESTION_LISTAS_PRECIOS_FULL_QA_V2
 @P_NIVEL_PRECIO='MAYOREOB',@P_FECHA_INICIO='20260910',
 @P_FECHA_FIN='99991231',@P_NIVEL_PRECIO_BASE='MAYOREOD',
 @P_VERSION=1,@COLUMNA_DCTO=NULL,
 @P_FACTOR_GLOBAL=1.30,@P_EXTENDER_MAYOR_100000=0,@P_SOLO_SIMULAR=1;
*/
